package sqlp

// Type of a `Token` generated by `Tokenizer`.
type Type byte

const (
	TypeInvalid Type = iota
	TypeText
	TypeWhitespace
	TypeQuoteSingle
	TypeQuoteDouble
	TypeQuoteGrave
	TypeCommentLine
	TypeCommentBlock
	TypeDoubleColon
	TypeOrdinalParam
	TypeNamedParam
	TypeParenOpen
	TypeParenClose
	TypeBracketOpen
	TypeBracketClose
	TypeBraceOpen
	TypeBraceClose
)

// True if zero. Used to detect end of tokenization.
func (self Type) IsInvalid() bool { return self == TypeInvalid }
